namespace MigrationWorkflow.Domain.Models;

/// <summary>
/// Reconciliation report generated by reconciliation agent
/// </summary>
public class ReconciliationReport
{
    public string ReportId { get; set; } = Guid.NewGuid().ToString();
    public string MigrationId { get; set; } = string.Empty;
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    
    // Count comparisons
    public int SourceRecordCount { get; set; }
    public int TargetRecordCount { get; set; }
    public int MismatchCount { get; set; }
    
    // Data quality metrics
    public double DataAccuracyPercentage { get; set; }
    public List<ReconciliationDiscrepancy> Discrepancies { get; set; } = new();
    
    // Summary
    public bool IsReconciled { get; set; }
    public string Summary { get; set; } = string.Empty;
}

public class ReconciliationDiscrepancy
{
    public string RecordId { get; set; } = string.Empty;
    public string FieldName { get; set; } = string.Empty;
    public string SourceValue { get; set; } = string.Empty;
    public string TargetValue { get; set; } = string.Empty;
    public string DiscrepancyType { get; set; } = string.Empty; // Missing, Mismatch, Extra
}
